name: Benchmarks

on:
  # Run on pushes to the main branch
  push:
    branches:
      - "master" # or "main"
  # Run on pull requests
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .tox
            ~/.cache/pip
          key: "py312-pyqt66-${{ matrix.os }}-3.12-${{ hashFiles('misc/requirements/requirements-*.txt') }}-${{ hashFiles('requirements.txt') }}"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Set up problem matchers
        run: "python scripts/dev/ci/problemmatchers.py py312-pyqt66 ${{ runner.temp }}"
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libyaml-dev libegl1-mesa libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-shape0 libxcb-cursor0
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U \
            -r misc/requirements/requirements-tox.txt \
            -r misc/requirements/requirements-dev.txt \
            -r misc/requirements/requirements-tests.txt \
            -r misc/requirements/requirements-pyqt-6.6.txt
          python -m pip install -e .

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          run: dbus-run-session pytest . --codspeed
